package main

// esperantoBakedIdent lists Esperanto TV shows whose first segment (_0000.ts, ~10s)
// is the old montage station ident that scripts/build_esperanto_tv_full.py used
// to concatenate in front of every show. The station skips that segment so
// the ident is not played on top of the between-programme bumper.
// Detected by comparing frame 100 of each _0000.ts with testcard/esperanto_ident0.ts
// (PSNR >= 30 dB); the segment boundary falls exactly on the end of the ident.
var esperantoBakedIdent = map[string]bool{
	"dok_estas_parto_01":    true,
	"dok_estas_parto_02":    true,
	"dok_estas_parto_03":    true,
	"dok_estas_parto_04a":   true,
	"dok_estas_parto_04b":   true,
	"dok_estas_parto_05":    true,
	"dok_estas_parto_06":    true,
	"ident_z_bumper":        true,
	"mv_akordo_printempas":  true,
	"mv_anjo_avemaria":      true,
	"mv_barok_vivriver":     true,
	"mv_berlinosenvi":       true,
	"mv_dankas_vivon":       true,
	"mv_deathnote_eo":       true,
	"mv_evangelion_eo":      true,
	"mv_gefratoj":           true,
	"mv_gijom_postrompiga":  true,
	"mv_haddad_niartas":     true,
	"mv_kajtielplu_dianto":  true,
	"mv_kajto_balancilo":    true,
	"mv_kajto_tohuvabohuo":  true,
	"mv_kolombino":          true,
	"mv_lafinavenk":         true,
	"mv_lamalpezadormo":     true,
	"mv_lpg_senpromese":     true,
	"mv_onepiece_eo":        true,
	"mv_patema_eo":          true,
	"mv_pokemon_eo":         true,
	"mv_rabu_lavivorozas":   true,
	"mv_roger_luna":         true,
	"mv_samideano":          true,
	"mv_sono_de_silento":    true,
	"mv_sufero":             true,
	"mv_superbazaro":        true,
	"mv_touhou_badapple_eo": true,
	"mv_yesterday_eo":       true,
	"mv_yvart_oeoe":         true,
	"pasporto_02":           true,
	"pasporto_14":           true,
	"pasporto_15":           true,
	"pasporto_16":           true,
	"senlime_s01e01":        true,
	"senlime_s01e02":        true,
	"senlime_s01e03":        true,
	"senlime_s01e04":        true,
	"senlime_s01e05":        true,
	"senlime_s01e06":        true,
	"senlime_s01e07":        true,
	"senlime_s01e08":        true,
	"senlime_s01e09":        true,
	"senlime_s01e10":        true,
	"senlime_s01e11":        true,
	"senlime_s01e12":        true,
	"senlime_s01e13":        true,
	"senlime_s01e14":        true,
	"senlime_s01e15":        true,
	"senlime_s01e16":        true,
}
